version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "ASA" 
    ports:
      - "5432:5432"
    volumes:
      - /home/banco/:/var/lib/postgresql/data
    networks:
      - postgres-network
networks:
  postgres-network:
    driver: bridge 
